/*
 * This source file was generated by the Gradle 'init' task
 */
package com.adrian.moneyledger;
import com.adrian.moneyledger.ui.LedgerApp;


public class App {

    public static void main(String[] args) 
    {
        LedgerApp app = new LedgerApp();
        app.run();
      

    }
}
